### ISSUE TITLE
Adopt repository changes

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/repEAT#26]
### Sub-tasks

- [x] Upgrade to new model version. 
- [x] Remove repository mocks. 
- [x] Change ˋRepositoryFactoryˋ. 
- [x] Change calls to new repository methods in view controllers.
