### ISSUE TITLE
Implement Household feature as PoC

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/repEAT#4]
Implement the feature to maintain a household in the app. Use standard controls where possible. Custom drawing and coloring can be omitted for now. Persistency can be mocked. 

### Sub-tasks

- [x] Domain model 
- [x] View controller to list persons
- [x] View controller to display, maintain and create a person
- [ ] ~~Delete all allergies when switched off~~(covered by #11)
- [x] Save a person
- [ ] Display allergies alphabetically
